// Run with: node scripts/generate-schema.js
// Regenerates sql/schema.sql from public/symptoms-data.js so the database
// columns always match the questionnaire items exactly.
const fs = require("fs");
const path = require("path");
const { GAP_SYMPTOMS, SAGIS_SYMPTOMS, SAGIS_YESNO } = require("../public/symptoms-data.js");

const lines = [];
lines.push("-- Auto-generated by scripts/generate-schema.js -- do not hand-edit column lists.");
lines.push("-- Run this once against your PostgreSQL database to create the table.");
lines.push("");
lines.push("DROP TABLE IF EXISTS responses;");
lines.push("");
lines.push("CREATE TABLE responses (");
lines.push("    id SERIAL PRIMARY KEY,");
lines.push("");
lines.push("    -- Part A: Patient Information");
lines.push("    name_initials TEXT,");
lines.push("    sex TEXT,");
lines.push("    age INTEGER,");
lines.push("    race TEXT,");
lines.push("    race_other TEXT,");
lines.push("    education_level TEXT,");
lines.push("    contact_number TEXT,");
lines.push("    smoking_status TEXT,");
lines.push("    wears_glasses TEXT,");
lines.push("");
lines.push("    -- Part B: SAGIS Questionnaire (0-4 severity scale per symptom)");
SAGIS_SYMPTOMS.forEach(s => {
    lines.push(`    sagis_${s.key} SMALLINT,`);
});
lines.push("");
lines.push("    -- Part B: additional Yes/No symptom checklist");
SAGIS_YESNO.forEach(item => {
    lines.push(`    sagis_${item.key} BOOLEAN,`);
});
lines.push("");
lines.push("    -- Part B: open-ended concerns");
lines.push("    sagis_main_concern TEXT,");
lines.push("    sagis_second_concern TEXT,");
lines.push("");
lines.push("    -- Part C: GAP Questionnaire (0-3 severity scale per symptom, video pictograms)");
GAP_SYMPTOMS.forEach(s => {
    lines.push(`    gap_${s.key} SMALLINT,`);
});
lines.push("");
lines.push("    -- Part E: Overall Feedback");
lines.push("    feedback_gap_helped SMALLINT,      -- 1-5 Likert");
lines.push("    feedback_comfortable SMALLINT,     -- 1-5 Likert");
lines.push("    easier_version TEXT,               -- 'sagis' | 'gap' | 'no_difference'");
lines.push("    other_comments TEXT,");
lines.push("");
lines.push("    submission_date TIMESTAMP DEFAULT NOW()");
lines.push(");");
lines.push("");

const outPath = path.join(__dirname, "..", "sql", "schema.sql");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, lines.join("\n"));
console.log("Wrote " + outPath);
