-- Auto-generated by scripts/generate-schema.js -- do not hand-edit column lists.
-- Run this once against your PostgreSQL database to create the table.

DROP TABLE IF EXISTS responses;

CREATE TABLE responses (
    id SERIAL PRIMARY KEY,

    -- Part A: Patient Information
    name_initials TEXT,
    sex TEXT,
    age INTEGER,
    race TEXT,
    race_other TEXT,
    education_level TEXT,
    contact_number TEXT,
    smoking_status TEXT,
    wears_glasses TEXT,

    -- Part B: SAGIS Questionnaire (0-4 severity scale per symptom)
    sagis_gerd SMALLINT,
    sagis_dysphagia SMALLINT,
    sagis_fullness SMALLINT,
    sagis_early_satiety SMALLINT,
    sagis_postprandial_pain SMALLINT,
    sagis_epigastric_pain SMALLINT,
    sagis_retrosternal_discomfort SMALLINT,
    sagis_pain_before_defecation SMALLINT,
    sagis_difficulty_defecating SMALLINT,
    sagis_constipation SMALLINT,
    sagis_loose_stool SMALLINT,
    sagis_incontinence SMALLINT,
    sagis_urgency SMALLINT,
    sagis_diarrhea SMALLINT,
    sagis_loss_of_appetite SMALLINT,
    sagis_abdominal_cramps SMALLINT,
    sagis_sickness SMALLINT,
    sagis_nausea SMALLINT,
    sagis_vomiting SMALLINT,
    sagis_bloating SMALLINT,
    sagis_flatulence SMALLINT,
    sagis_belching SMALLINT,

    -- Part B: additional Yes/No symptom checklist
    sagis_headache BOOLEAN,
    sagis_back_pain BOOLEAN,
    sagis_chronic_fatigue BOOLEAN,
    sagis_depression_yn BOOLEAN,
    sagis_sleep_disturbance BOOLEAN,
    sagis_excessive_anxiety BOOLEAN,

    -- Part B: open-ended concerns
    sagis_main_concern TEXT,
    sagis_second_concern TEXT,

    -- Part C: GAP Questionnaire (0-3 severity scale per symptom, video pictograms)
    gap_gerd SMALLINT,
    gap_dysphagia SMALLINT,
    gap_fullness SMALLINT,
    gap_early_satiety SMALLINT,
    gap_postprandial_pain SMALLINT,
    gap_epigastric_pain SMALLINT,
    gap_retrosternal_discomfort SMALLINT,
    gap_pain_before_defecation SMALLINT,
    gap_difficulty_defecating SMALLINT,
    gap_constipation SMALLINT,
    gap_loose_stool SMALLINT,
    gap_incontinence SMALLINT,
    gap_urgency SMALLINT,
    gap_diarrhea SMALLINT,
    gap_loss_of_appetite SMALLINT,
    gap_abdominal_cramps SMALLINT,
    gap_sickness SMALLINT,
    gap_nausea SMALLINT,
    gap_vomiting SMALLINT,
    gap_bloating SMALLINT,
    gap_flatulence SMALLINT,
    gap_belching SMALLINT,
    gap_anxiety SMALLINT,
    gap_depression SMALLINT,

    -- Part E: Overall Feedback
    feedback_gap_helped SMALLINT,      -- 1-5 Likert
    feedback_comfortable SMALLINT,     -- 1-5 Likert
    easier_version TEXT,               -- 'sagis' | 'gap' | 'no_difference'
    other_comments TEXT,

    submission_date TIMESTAMP DEFAULT NOW()
);
